Change the mechanism to access mounted files from file based to sector based
Konamiman/Nextor pull request #93
Opened 2021-09-01 09:24 UTC by Konamiman

WIP

2022-01-13 18:45 UTC, theNestruo requested changes

2022-01-13 18:45 UTC, theNestruo commented on source/kernel/bank2/val.mac
> +		pop iy
Minor optimization: replace `push hl / push iy / push hl / pop iy` with `push hl / push hl / ex (sp), iy`

2022-01-13 18:45 UTC, theNestruo commented on source/kernel/bank4/partit.mac
> +	pop hl
Minor optimization: `push ix / ex (sp), hl`

2022-03-22 09:07 UTC, merged

2022-03-22 11:04 UTC, grauw commented
Is there an easy way to defragment a file?